[2022-10-26 14:48:15,409] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag.also_run_this manual__2022-10-26T14:48:09.454928+00:00 [queued]>
[2022-10-26 14:48:15,417] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag.also_run_this manual__2022-10-26T14:48:09.454928+00:00 [queued]>
[2022-10-26 14:48:15,417] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:48:15,417] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-26 14:48:15,418] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:48:15,430] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): also_run_this> on 2022-10-26 14:48:09.454928+00:00
[2022-10-26 14:48:15,432] {standard_task_runner.py:52} INFO - Started process 5459 to run task
[2022-10-26 14:48:15,435] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag', 'also_run_this', 'manual__2022-10-26T14:48:09.454928+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpn5gv9gog', '--error-file', '/tmp/tmpd_px7zvu']
[2022-10-26 14:48:15,436] {standard_task_runner.py:80} INFO - Job 158: Subtask also_run_this
[2022-10-26 14:48:15,493] {task_command.py:369} INFO - Running <TaskInstance: dag.also_run_this manual__2022-10-26T14:48:09.454928+00:00 [running]> on host cf01c04ee00d
[2022-10-26 14:48:15,571] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T14:48:09.454928+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-26T14:48:09.454928+00:00
[2022-10-26 14:48:15,572] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-26 14:48:15,573] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ls']
[2022-10-26 14:48:15,579] {subprocess.py:85} INFO - Output:
[2022-10-26 14:48:15,580] {subprocess.py:96} INFO - Command exited with return code 0
[2022-10-26 14:48:15,616] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dag, task_id=also_run_this, execution_date=20221026T144809, start_date=20221026T144815, end_date=20221026T144815
[2022-10-26 14:48:15,647] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:48:15,684] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
