[2022-10-26 14:15:03,088] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag.fetch_file scheduled__2022-10-26T14:00:00+00:00 [queued]>
[2022-10-26 14:15:03,097] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag.fetch_file scheduled__2022-10-26T14:00:00+00:00 [queued]>
[2022-10-26 14:15:03,097] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:15:03,097] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-26 14:15:03,098] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:15:03,112] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): fetch_file> on 2022-10-26 14:00:00+00:00
[2022-10-26 14:15:03,114] {standard_task_runner.py:52} INFO - Started process 4527 to run task
[2022-10-26 14:15:03,117] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag', 'fetch_file', 'scheduled__2022-10-26T14:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpzdoq03r5', '--error-file', '/tmp/tmpgrz1wylt']
[2022-10-26 14:15:03,118] {standard_task_runner.py:80} INFO - Job 136: Subtask fetch_file
[2022-10-26 14:15:03,183] {task_command.py:369} INFO - Running <TaskInstance: dag.fetch_file scheduled__2022-10-26T14:00:00+00:00 [running]> on host cf01c04ee00d
[2022-10-26 14:15:03,254] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=fetch_file
AIRFLOW_CTX_EXECUTION_DATE=2022-10-26T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-26T14:00:00+00:00
[2022-10-26 14:15:05,494] {python.py:173} INFO - Done. Returned value was: None
[2022-10-26 14:15:05,510] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dag, task_id=fetch_file, execution_date=20221026T140000, start_date=20221026T141503, end_date=20221026T141505
[2022-10-26 14:15:05,658] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:15:05,694] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
